name:                github-org-repos-resource
version:             0.1.0.0
github:              "githubuser/github-org-repos-resource"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.org
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/github-org-repos-resource#readme>

dependencies:
- base >= 4.7 && < 5
- github
- text
- bytestring
- aeson
- unordered-containers
- SHA
- vector
- either

library:
  source-dirs: src

executables:
  check:
    main:                Main.hs
    source-dirs:         app/check
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - github-org-repos-resource

  in:
    main:                Main.hs
    source-dirs:         app/in
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - github-org-repos-resource

  out:
    main:                Main.hs
    source-dirs:         app/out
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - github-org-repos-resource



tests:
  github-org-repos-resource-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - github-org-repos-resource
